### ISSUE TITLE
Hunter: Revisit traps 

### ISSUE THREAD

**Issue by Frogvall** [WC5E/Warcraft-5e-Conversion#594]
I think there is room for improvements when it comes to hunter traps. Instead of writing it all from scratch (again), I'm going to copy from a chat I had with Silverblade about it. 

Auvreannia:
Btw, my idea for hunter traps was something like this:
All of them are reactions with triggers. Example Frost Trap:
When an enemy moves within 5 feet of you, you can use your reaction to trap it in ice. The target must make a dex saving throw...

The fluff would be "Ha, I cleverly placed a trap where I knew you'd be walking."

This was to avoid having to deal with positioning micro management, and not to put the DM in the position to have to motivate every time he moves, why he didn't step in the trap (or stupidly walk into it to avoid having that discussion).

Silverblade:
That absolutely takes care of the obvious design problem with traps.

Auvreannia:
Thanks. I thought it pretty clever

Silverblade:
And making it very close to you cuts down on some more ridiculous shenanigans.
If you really want to add some 'realism' (for whatever that means), you could say that you had to have not moved since your last turn, or something.
It's a good idea!
There's just not enough tactical movement stuff in 5E to do traps 'honestly', which is a problem when that is absolutely the defining aspect of survival.
Sure, there's other things you can draw from instead, but far and away the defining thing about survival has always been traps.
Heck, make them reaction-based when someone gets close also encourages a more close combat-type playstyle, playing into the current role of survival as the melee hunter.
I'm rather taken with this idea now, TBH

**Comment by orjanbp** [comment]
Sounds like a really good solution for making traps be more useful when a reature comes right at the hunter, allowing that one extra trick up the sleeve to push back, yeah. That's a pretty cool niche around it. 

Are you thinking this as an additional way to use them, or as a total replacement to? Because personally I feel like the two could easily work side by side without it being any real worry, and right now I'd definitely imagine that what most Survival hunters is doing is to just throw the trap right at the target (with the 30 ft. range) instead of trying to predict where the target will be at.

Or they're putting it where the obvious choke point is; like an Ice Trap in front of a door to keep creatures escaping through it. 

We've got a number of trap (Explosive, Immolation, Venom, Blinding) that don't sound very appealing to use in a melee. And just saying "you yourself aren't affected" doesn't sound that convincing? To me it definitely doesn't.

**Comment by Frogvall** [comment]
This suggestion was actually my original one, but it disappeared in a night of 2000 messages :P

I'd suggest a complete overhaul of the traps. Using reactions as the primary way of using them. The traps would have to be rewritten to fit this way of applying them. An immolation trap could be a cone instead of a burst (shaped charge) for example.

If we feel like we want a more active way of applying traps at some point, we can introduce a trap launcher at a later level, letting you "throw" a trap as an action, instead of placing it close as a reaction.

But the primary goal here is to completely remove the need for positioning, which is not very well handled by dnd 5e (unless playing on a grid, but even then it puts the GM in a weird position).

**Comment by orjanbp** [comment]
Alright! Rewriting the traps to work with using a reaction for them makes a lot more sense, haha, because personally I was wondering how and why a hunter would deal with an exploding trap that they'd be caught in the heat of! 

Personally I feel like both could easily work side by side. They don't have to be mutual exclusive, right? Changing them up like this solves the problem for melee hunters, but if we changed them entirely then we would be taking something pretty big away from the ranged Survival hunters. They that are using them just fine right now, and sound like they're having fun with it, by launching the trap off next to their target to detonate there. 

And if we did that, maybe the action difference would make sense? The difference between using your Reaction to release it in a cone in front of you, or your Action to throw out something with a bigger area of effect (not counting the traps that just have a flat single target effect).

**Comment by Frogvall** [comment]
That would be the trap launcher. But we don't need a "placing" mechanic for that. It's basically a reaction to detonate a trap close or an action to detonate it on top of someone. What it takes away is the "place it in a choke point and have people walk into it" part, but I think that's a very narrow use that does not warrant it's own mechanics.

**Comment by orjanbp** [comment]
Yeah, it honestly feels like the choke-point placement is maybe 1% of how people use traps, and that people right now just literally throw it into an empty space next to the creature they want to affect.

But choosing between throwing a trap way out there as a ranged attack, or pulling it out of nowhere on a Reaction when a creature gets too close. It sounds really, really cool!

**Comment by Tyloris** [comment]
Fixed and implemented in the latest hunter revision.
